apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}

