trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  imageName: recruitment-app
  imageTag: $(Build.BuildId)

steps:
- checkout: self

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: GRC-DockerRS # your ACR service connection name
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      $(imageTag)
